# typed: false
# frozen_string_literal: true

# Binary formula: installs the prebuilt `kannaka` release binary for the host
# platform; Homebrew verifies the pinned sha256 digests against the download.
# Linux binaries are static musl, so they run on any distro Homebrew-on-Linux
# supports.
#
# GENERATED by publish-channels.yml in NickFlach/kannaka-memory — edit there.
class Kannaka < Formula
  desc "Wave-interference (Holographic Resonance Medium) memory for AI agents"
  homepage "https://github.com/NickFlach/kannaka-memory"
  version "0.16.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/NickFlach/kannaka-memory/releases/download/v0.16.0/kannaka-macos-aarch64"
      sha256 "4d08d65b6a83aebd66fdeb2c706fe97413d4b78b71c7d2b0c740fce5cc2d2418"
    end
    on_intel do
      url "https://github.com/NickFlach/kannaka-memory/releases/download/v0.16.0/kannaka-macos-x86_64"
      sha256 "b79a6bbdc5b123dc504ea0c47cce41a85dc55e4705368c787980b5ec3f1d1303"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/NickFlach/kannaka-memory/releases/download/v0.16.0/kannaka-linux-aarch64"
      sha256 "699b89ef68be286cd67e11fb33025531d8b1453c896e5a5d0705ea200a2fdc17"
    end
    on_intel do
      url "https://github.com/NickFlach/kannaka-memory/releases/download/v0.16.0/kannaka-linux-x86_64"
      sha256 "712e6a20403731c297703af30dfa4889541fdc2a066d75cb488672bc56f8eab2"
    end
  end

  def install
    bin.install Dir["kannaka-*"].first => "kannaka"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kannaka --version")
  end
end
