# typed: false
# frozen_string_literal: true

# Binary formula: installs the prebuilt `kannaka` release binary for the host
# platform; Homebrew verifies the pinned sha256 digests against the download.
# Linux binaries are static musl, so they run on any distro Homebrew-on-Linux
# supports.
#
# GENERATED by publish-channels.yml in NickFlach/kannaka-memory — edit there.
class Kannaka < Formula
  desc "Wave-interference (Holographic Resonance Medium) memory for AI agents"
  homepage "https://github.com/NickFlach/kannaka-memory"
  version "0.15.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/NickFlach/kannaka-memory/releases/download/v0.15.3/kannaka-macos-aarch64"
      sha256 "4edf49123479301b958efe72a6cf05f607b733a8c7d91d637aaa745c84958ecf"
    end
    on_intel do
      url "https://github.com/NickFlach/kannaka-memory/releases/download/v0.15.3/kannaka-macos-x86_64"
      sha256 "3ab43c8d6fb7fb0038e112b6c4bd6639dd499bb7d9b382cddfe003882f6c5014"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/NickFlach/kannaka-memory/releases/download/v0.15.3/kannaka-linux-aarch64"
      sha256 "e53d17ff178a2b87878b2a7bec7153cb1ce6dee00330ecd859322de5787b924d"
    end
    on_intel do
      url "https://github.com/NickFlach/kannaka-memory/releases/download/v0.15.3/kannaka-linux-x86_64"
      sha256 "611764d15bc506f9165b20d29ec664d95c5ac6456f65969fcec13a99b42be3b8"
    end
  end

  def install
    bin.install Dir["kannaka-*"].first => "kannaka"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kannaka --version")
  end
end
