# typed: false
# frozen_string_literal: true

# Binary formula: installs the prebuilt `kannaka` release binary for the host
# platform; Homebrew verifies the pinned sha256 digests against the download.
# Linux binaries are static musl, so they run on any distro Homebrew-on-Linux
# supports.
#
# GENERATED by publish-channels.yml in NickFlach/kannaka-memory — edit there.
class Kannaka < Formula
  desc "Wave-interference (Holographic Resonance Medium) memory for AI agents"
  homepage "https://github.com/NickFlach/kannaka-memory"
  version "0.13.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/NickFlach/kannaka-memory/releases/download/v0.13.0/kannaka-macos-aarch64"
      sha256 "d4c322766108c091e0cc9fa2ff599cb798966a246614055ce34812166107ad4e"
    end
    on_intel do
      url "https://github.com/NickFlach/kannaka-memory/releases/download/v0.13.0/kannaka-macos-x86_64"
      sha256 "b5292f9ae9343e7d353b6c4a54d316875cf2189770b418f4e2de812865b20893"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/NickFlach/kannaka-memory/releases/download/v0.13.0/kannaka-linux-aarch64"
      sha256 "562d6eba6ddd7841afd0b258d64a0cea80d7299c652fc80dc64583a14856edc3"
    end
    on_intel do
      url "https://github.com/NickFlach/kannaka-memory/releases/download/v0.13.0/kannaka-linux-x86_64"
      sha256 "6234c4ff43e4fb250b8c7eed6e62c9363935cf17587bf638aa439ac89f3c0b3d"
    end
  end

  def install
    bin.install Dir["kannaka-*"].first => "kannaka"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kannaka --version")
  end
end
